// Copyright (c) 2022 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: liberty-deepdive
:page-layout: guide-multipane
:page-duration: 100 minutes
:page-releasedate: 2022-03-31
:page-essential: false
:page-description: Learn how to use Liberty to develop microservice.
:page-tags: []
:page-related-guides: []
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:imagesdir: /img/guide/{projectid}
:source-highlighter: prettify
:page-seo-title: Implementing a microservice using Jakarta EE and MicroProfile API
:page-seo-description: A tutorial with examples on how to implement a microservice using Jakarta EE and Eclipse MicroProfile API.
:guide-author: Open Liberty
= Liberty deepdive class

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Liberty is a cloud-optimized Java runtime that is fast to start up with a low memory footprint and a dev mode for quick iteration. Adding and removing features to adopt the latest open cloud-native Java API like MicroProfile and Jakarta EE are easy with Liberty. Liberty's zero migration lets you focus on what's important and not the APIs changing under you.

== What you'll learn

You will learn how to build...

== Additional prerequisites

Before you begin, Docker needs to be installed before starting the module of Presisting Data.
For installation instructions, refer to the https://docs.docker.com/get-docker/[official Docker documentation^].
You'll build and run the application in Docker containers.

Make sure to start your Docker daemon before you proceed.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

== Getting started

Create a maven project by OL starter.

Develop an RESTful microservice.

== Documenting APIs

Document the RESTful APIs by using MicroProfile OpenAPI

==  Configuring the microservice

configure the context root and port

provide external configuration to the microservice using MicroProfile Config

== Persisting data

use JPA to access and persist data to a database for the microservice

== Securing RESTful APIs

// File 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-securing/src/main/liberty/config/server.xml[]
----

// File 1
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-securing/src/main/java/io/openliberty/deepdive/rest/SystemResource.java[]
----

Now you will secure your RESTful APIs.

Begin by adding some users and user groups to your application by adding a [hotspot=basicregistry file=0]`basicRegistry` to your [hotspot file=0]`server.xml` file.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `server.xml` file.#
`module-securing/src/main/liberty/config/server.xml`
----

The [hotspot=basicregistry file=0]`basicRegistry` contains a list of all users for the application and their passwords, as well as all of the user groups. The [hotspot=myadmins file=0]`myAdmins` group tells the application which of the users are in the `myAdmins` group, and the [hotspot=myusers file=0]`myUsers` group tells the application which users are in the `users` group.

The [hotspot=securityrole file=0]`securityRole` maps the `admin` role to the [hotspot=myadmins file=0]`myAdmins` group, meaning that all users in the `myAdmins` group will have the admin role. Similarly, the `user` role is mapped to the [hotspot=myusers file=0]`myUsers` group, meaning all users in the `myUsers` group will have the user role.

Your application will have the following users and passwords:

[cols="<35, ^200, ^200"]
|===
| *Username* | *Password* | *Role*
| bob | bobpwd | admin, user
| alice | alicepwd | user
|===

The [hotspot=keystore file=0]`keyStore` is a repository of security certificates used for SSL encryption. The `id` is a unique configuration id, which is set to `defaultKeyStore`, and the `password` is used to load the keystore file. The value can be stored in clear text or encoded form.

Now you will secure the `inventory` service.

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`module-securing/src/main/java/io/openliberty/deepdive/rest/SystemResource.java`
----

This class now has role-based access control. The role names that are used in the [hotspot=put hotspot=delete file=1]`@RolesAllowed` annotations are mapped to group names in the groups claim of the `JWT`, which results in an authorization decision wherever the security constraint is applied.

The [hotspot=putEndpoint file=1]`/{hostname}` endpoint annotated with the [hotspot=putEndpoint file=1]`@PUT` annotation updates a system in the inventory. This `PUT` endpoint is annotated with the [hotspot=put file=1]`@RolesAllowed({ "admin", "user" })` annotation. Only authenticated users with the role of `admin` or `user` can access this endpoint.

The [hotspot=deleteEndpoint file=1]`/{hostname}` endpoint annotated with the [hotspot=deleteEndpoint file=1]`@DELETE` annotation removes a system from the inventory. This `DELETE` endpoint is annotated with the [hotspot=delete file=1]`@RolesAllowed({ "admin" })` annotation. Here, only authenticated users with the role of `admin` can access this endpoint.

You can manually check that the `inventory` service is secure by making requests to each of the endpoints.

Before we do this, we must add a system to the inventory.
Try adding a system via the `POST` endpoint `/systems` using the following command:

[role='command']
----
curl -X POST http://localhost:9080/inventory/api/systems -d 'hostname=localhost&osName=mac&javaVersion=11&heapSize=1'
----

You should expect the following response:

[source role=no_copy]
----
{ "ok" : "localhost was added." }
----

This calls the `/systems` endpoint and adds a new system `localhost` to the inventory.
We can validate that this has worked by calling the `/systems` endpoint with a `GET` request to retrieve all the systems in the inventory, with the following curl command:

[role='command']
----
curl http://localhost:9080/inventory/api/systems
----

You should now expect the following response:

[source, role=no_copy]
----
[{"heapSize":1,"hostname":"localhost","javaVersion":"11","osName":"mac"}]
----

Now we will try calling our secure `PUT` endpoint to update the system we just added, with the following curl command:

[role='command']
----
curl -k --user alice:alicepwd -X PUT https://localhost:9443/inventory/api/systems/localhost -d 'osName=mac&javaVersion=17&heapSize=2'
----

As this endpoint is accessible to the groups `user` and `admin` we have logged in with `user` credentials and updated the system.

You should see the following response:

[source, role=no_copy]
----
{ "ok" : "localhost was updated." }
----

This means that you have successfully logged in as an authenticated `user`, and that the endpoint works as expected.

Now try calling the `DELETE` endpoint. As this endpoint is only accessible to `admin` users, we should expect this to fail if we attempt to access it with a user in the `user` group.

We can check that our application is secured against these requests with the following command:

[role='command']
----
curl -k --user alice:alicepwd -X DELETE https://localhost:9443/inventory/api/systems/localhost
----

As `alice` is part of the `user` group, this request should not work. In your dev mode console, you should expect the following output:

[source, role=no_copy]
----
jakarta.ws.rs.ForbiddenException: Unauthorized
----

Now we will attempt to call this endpoint with an authenticated `admin` user, which should work correctly.
Enter the following curl command:

[role='command']
----
curl -k --user bob:bobpwd -X DELETE  https://localhost:9443/inventory/api/systems/localhost
----

You should see the following response:

[source, role=no_copy]
----
{ "ok" : "localhost was removed." }
----

This means that your endpoint is secure. Validate that it works correctly by calling the `/systems` endpoint with the following curl command:

[role='command']
----
curl http://localhost:9080/inventory/api/systems
----

You should see the following output:

[source, role=no_copy]
----
[]
----

This shows that the endpoints work as expected and that the system you added has been successfully deleted.

== Consuming the secured RESTful APIs by JWT

// File 0
SystemClient.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/src/main/java/io/openliberty/deepdive/rest/client/SystemClient.java[]
----

// File 1
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/src/main/java/io/openliberty/deepdive/rest/SystemResource.java[]
----

// File 2
UnknownUriException.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/src/main/java/io/openliberty/deepdive/rest/client/UnknownUriException.java[]
----

// File 3
UnknownUriExceptionMapper.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/src/main/java/io/openliberty/deepdive/rest/client/UnknownUriExceptionMapper.java[]
----

// File 4
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/src/main/liberty/config/server.xml[]
----

// File 5
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/module-jwt/pom.xml[]
----

You will now implement JSON Web Tokens (JWT) and configure them as Single Sign On (SSO) cookies in order to consume the RESTful APIs. The JWT that you will generate will be used to communicate securely between the `inventory` and `system` microservice. The `inventory` service returns a list of systems stored on the server, and builds a JWT, and makes authorized requests to the `system` service for the JVM system properties.

The `system` microservice has been provided for you.

Create a RESTful client interface for the `inventory` service.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemClient` interface.#
`module-jwt/src/main/java/io/openliberty/deepdive/rest/client/SystemClient.java`
----

This interface declares methods for accessing each of the endpoints that are set up for you in the `system` service. The MicroProfile Rest Client feature automatically builds and generates a client implementation based on what is defined in the [hotspot file=0]`SystemClient` interface. You don’t need to set up the client and connect with the remote service.

Now create the required exception classes that will be used when building the `SystemClient` instance.

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `UnknownUriException` class.#
`module-jwt/src/main/java/io/openliberty/deepdive/rest/client/UnknownUriException.java`
----

This class is an exception which is thrown when an unknown URI is passed to the `SystemClient`.

[role="code_command hotspot file=3", subs="quotes"]
----
#Create the `UnknownUriExceptionMapper` class.#
`module-jwt/src/main/java/io/openliberty/deepdive/rest/client/UnknownUriExceptionMapper.java`
----

This class implements the `UnknownUriException` class which you just created.

Now update the `SystemResource` class in the `inventory` service to add a new endpoint to consume the secured `system` service.

[role="code_command hotspot file=1", subs="quotes"]
----
#Replace the `SystemResource` class.#
`module-jwt/src/main/java/io/openliberty/deepdive/rest/SystemResource.java`
----

The [hotspot=getSystemClient file=1]`getSystemClient` method builds and returns a new instance of the `SystemClient` class for the given hostname. 

The new [hotspot=addSystemClient file=1]`/client/{hostname}` `POST` endpoint uses this method to create a rest client called [hotspot=customRestClient file=1]`customRestClient` to consume the `system` service. This endpoint takes the properties of the JVM system and adds them to the inventory. 

The [hotspot=jwt file=1]`JWT` is also produced inside this method and is passed via a parameter to the endpoints of the [hotspot=customRestClient file=1]`customRestClient` to get the properties of the JVM system. This system is then added to the inventory.

The [hotspot=getSystemClient file=1]`getSystemClient` method registers the `UnknownUriExceptionMapper` class which you created to the new rest client.  

Next, add the JSON Web Token (Single Sign On) feature to the server configuration file for the `inventory` service.

[role="code_command hotspot file=4", subs="quotes"]
----
#Replace the `server.xml` file.#
`module-jwt/src/main/liberty/config/server.xml`
----

The [hotspot=jwtSso file=4]`jwtSso` feature adds the libraries that are required for JWT SSO implementation.
Add the [hotspot=keyStore file=4]`keyStore` to your server configuration file.
Configure the `jwtSso` feature by adding the [hotspot=jwtBuilder file=4]`jwtBuilder` configuration to your `server.xml`.

The `keyStore` must be the same in both your `system` and `inventory` microservice. As the configured `system` service is already provided for you, copy the key store file from your `system` service to your `inventory` service.

Copy the `key.p12` file from your `system` directory to your `module-jwt` directory:

[role='command']
----
cp ../finish/system/src/main/liberty/config/resources/security/key.p12 src/main/liberty/config/resources/security/key.p12
----

Now configure the https port in the pom file.

[role="code_command hotspot file=5", subs="quotes"]
----
#Replace the `pom.xml` file.#
`module-jwt/pom.xml`
----

Configure the https port by setting the [hotspot=https file=5]`<liberty.var.client.https.port>` to [hotspot=https file=5]`9444`.

You can check that the JWT is set up by making requests to the new endpoint you created. 

Ensure both your `system` and `inventory` microservices are running.

[role='command']
----
cd module-jwt
mvn liberty:run
----

Open up a new terminal and run your `system` microservice from the `finish` directory.

[role='command']
----
cd ../finish/system
mvn liberty:run
----

First attempt to make an authorized request to the new `/client/{hostname}` endpoint.
As this endpoint is restricted to `admin` you should use the login credentials for `bob` as it is in the `admin` group.

[role='command']
----
curl -X 'POST' 'https://localhost:9443/inventory/api/systems/client/localhost' -H 'accept: */*' -d '' -k --user bob:bobpwd
----

You should expect the following output:

[source, role='no_copy']
----
{ "ok" : "localhost was added." }
----

You can verify that this endpoint works as expected by running the following command:

[role='command']
----
curl -X 'GET' 'https://localhost:9443/inventory/api/systems' -H 'accept: application/json'
----

You should expect to see your system listed in the output.

[source]
----
[
  {
    "heapSize": 8589934592,
    "hostname": "localhost",
    "javaVersion": "16.0.1",
    "osName": "Mac OS X"
  }
]
----

== Adding health checks

use MicroProfile Health to report the health status of the microservice

== Providing metrics

use MicroProfile Metrics to provide metrics from the microservice

== Testing the microservice

use test containger to test the microservice

== Building the container 

develop the microservice under container environment

package the microservice

build a container for the microservice

== Deploying the microservice to Kubernetes

install Open Liberty operator to Kubernetes

deploy the microservice to Kubernetes

== Support Licensing

use WebSphere Liberty


== Great work! You're done!

You just learnt to build a microservice in Open Liberty!

include::{common-includes}/attribution.adoc[]
